### ISSUE TITLE
wget build failure

### ISSUE THREAD

**Issue by mmatongo** [kiss-community/repo-community#234]
```sh
/usr/bin/ld: warning: libicuuc.so.67, needed by /usr/lib/gcc/x86_64-pc-linux-musl/10.2.0/../../../../lib/libpsl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicudata.so.67, needed by /usr/lib/gcc/x86_64-pc-linux-musl/10.2.0/../../../../lib/libpsl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-musl/10.2.0/../../../../lib/libpsl.so: undefined reference to `ucnv_open_67'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-musl/10.2.0/../../../../lib/libpsl.so: undefined reference to `uidna_nameToASCII_67'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-musl/10.2.0/../../../../lib/libpsl.so: undefined reference to `ucnv_close_67'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-musl/10.2.0/../../../../lib/libpsl.so: undefined reference to `u_strToLower_67'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-musl/10.2.0/../../../../lib/libpsl.so: undefined reference to `u_strFromUTF8_67'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-musl/10.2.0/../../../../lib/libpsl.so: undefined reference to `u_strToUTF8_67'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-musl/10.2.0/../../../../lib/libpsl.so: undefined reference to `ucnv_toUChars_67'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-musl/10.2.0/../../../../lib/libpsl.so: undefined reference to `uidna_openUTS46_67'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-musl/10.2.0/../../../../lib/libpsl.so: undefined reference to `uidna_close_67'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1861: wget] Error 1
make[3]: Leaving directory '/home/dm/.cache/kiss/proc/14600/build/wget/src'
make[2]: *** [Makefile:1760: all] Error 2
make[2]: Leaving directory '/home/dm/.cache/kiss/proc/14600/build/wget/src'
make[1]: *** [Makefile:1707: all-recursive] Error 1
make[1]: Leaving directory '/home/dm/.cache/kiss/proc/14600/build/wget'
make: *** [Makefile:1659: all] Error 2
```

`wget` fails to build on my system with `icu` version 68.2

**Comment by git-bruh** [comment]
Your `libpsl` might be linked against an old version of icu, latest icu is `68.2` (`/usr/lib/libicudata.so.68.2
`) hence the missing symbols. Rebuilding `libpsl` and then `wget` should fix it. Build works fine here.

**Comment by mmatongo** [comment]
> Your `libpsl` might be linked against an old version of icu, latest icu is `68.2` (`/usr/lib/libicudata.so.68.2 `).

I figured that as well, managed to build it a while ago.
Wouldn't incrementing the build number solve that seeing as it has to relink?
